### ISSUE TITLE
APP CRASH on Ubuntu 18.04 on hello,world

### ISSUE THREAD

**Issue by vincent456** [DynamoRIO/drmemory#2110] opened 2018-08-04 00:28 UTC
Brand new Ubuntu 18.04.1 64-bits. Like the title said, the program segfault when I make it test a simple helloworld using gcc -m32 source.c then drmemory -- ./a.out . 
Also notice that when I omit the -m32 flag, drmemory runs fine with no errors but it doesn't produce any output (not even a result.txt, only a symcache and a dynamorio folder, both empty) and doesn't run the a.out program (no printf).

**Comment by derekbruening** [comment] 2018-08-04 00:35
What happens with the series of options at https://github.com/DynamoRIO/drmemory/wiki/Debugging#narrowing-down-the-source-of-the-problem ?

**Comment by derekbruening** [comment] 2018-08-04 22:15
Providing the precise pasted output showing the command and all of its output would be useful

**Comment by galgalesh** [comment] 2018-08-27 12:34
I have the same issue, Ubuntu 18.04 with a trivially simple program. I have the same effect with 2.0 and 1.11.0, both with 32-bit and 64-bit binaries.

```bash
/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/bin64/drmemory -v -no_count_leaks -no_track_allocs -- ./adfgx
INFO: targeting application: "/home/merlijn/Desktop/brunotest/adfgx"
INFO: app cmdline: "./adfgx" 
INFO: logdir is "/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/drmemory/logs"
INFO: symcache_dir is "/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/drmemory/logs/symcache"
INFO: DynamoRIO configuration directory is /home/merlijn/.dynamorio
INFO: configuring adfgx pid=27198 dr_ops="-disable_traces -bb_single_restore_prefix -max_bb_instrs 256 -vm_size 256M -no_enable_reset -logdir `/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/drmemory/logs/dynamorio` "
INFO: configuring client "/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/bin64/release/libdrmemorylib.so" ops="`-no_count_leaks` `-no_track_allocs` -logdir `/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/drmemory/logs` -symcache_dir `/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/drmemory/logs/symcache` -resfile 27198 "


# no log files
$ tree /home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/drmemory/logs
/home/merlijn/Downloads/DrMemory-Linux-2.0.0-RC2/drmemory/logs
├── codecache
│   └── README.txt
├── dynamorio
├── README.txt
└── symcache
```

**Comment by derekbruening** [comment] 2018-08-27 14:56
Please try the most recent package which is the "cronbuild" at https://github.com/DynamoRIO/drmemory/releases/tag/cronbuild-1.11.17622

**Comment by galgalesh** [comment] 2018-08-27 15:18
That gets me a bit further, but it doesn't do what I expect.

```
$ g++ -g leak.cpp -o leak
$ /home/merlijn/Downloads/DrMemory-Linux-1.11.17622-1/bin64/drmemory -- ./leak
~~Dr.M~~ Dr. Memory version 1.11.17622
~~Dr.M~~
~~Dr.M~~ NO ERRORS FOUND:
~~Dr.M~~       0 unique,     0 total unaddressable access(es)
~~Dr.M~~       0 unique,     0 total uninitialized access(es)
~~Dr.M~~       0 unique,     0 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of still-reachable allocation(s)
~~Dr.M~~          (re-run with "-show_reachable" for details)
~~Dr.M~~ Details: /home/merlijn/Downloads/DrMemory-Linux-1.11.17622-1/drmemory/logs/DrMemory-leak.9996.000/results.txt
Segmentation fault (core dumped)
```

The program:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


void leak(){
    char *str = new char[200];
}

int main(int argc, char *argv[])
{
  leak();
  return 0;
}
```

[DrMemory-leak.9996.000.zip](https://github.com/DynamoRIO/drmemory/files/2324441/DrMemory-leak.9996.000.zip)

Am I doing something wrong or is this a bug?

**Comment by derekbruening** [comment] 2018-08-27 16:36
The 1.11.17622 cronbuild works for 64-bit apps for my 18.04 which is at:
```
$ uname -a
Linux ubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

32-bit apps have a crash due to vsyscall parsing which is https://github.com/DynamoRIO/dynamorio/issues/2945.  If you run debug build plain DR you should see that assert:

```
$ DrMemory-Linux-2.0.0-RC2/dynamorio/bin32/drrun -debug -- ./leak_indirect
<Starting application /home/derek/leak_indirect (7509)>
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/derek/DrMemory-Linux-2.0.0-RC2/dynamorio/lib32/debug/libdynamorio.so' 0xf7c1242c
>
<Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Application /home/derek/leak_indirect (7509).  Internal Error: DynamoRIO debug check failure: /drmemory_package/dynamorio/core/arch/arch.c:3059 vsyscall_page_start != NULL && vsyscall_page_start == (app_pc) PAGE_START(instr_get_raw_bits(instr))
(Error occurred @1912 frags)
```

There is a new build here https://github.com/DynamoRIO/drmemory/releases/tag/cronbuild-1.11.17770A which fixes the vsyscall issue.  Does it fix your 64-bit issue (the one I could not reproduce)?

**Comment by derekbruening** [comment] 2018-08-28 05:06
You could be hitting #2083 for which this is a workaround: `-dr_ops "-no_vm_base_near_app"`

**Comment by galgalesh** [comment] 2018-08-28 11:36
Thanks! The new build indeed fixes the vsyscall issue but it doesn't fix the 64bit issue.

Using the `-dr_ops "-no_vm_base_near_app"` workaround fixes the 64bit crash and it also shows the memory leak, so I expect it's #2083.

In case it's useful, this is the debug output of the 64bit binary:

```
$ /home/merlijn/Downloads/DrMemory-Linux-1.11.17770-1/dynamorio/bin64/drrun -debug -- ./leak
<Starting application /home/merlijn/Desktop/brunotest/leak (23659)>
<Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/merlijn/Downloads/DrMemory-Linux-1.11.17770-1/dynamorio/lib64/debug/libdynamorio.so' 0x00007fbebf2cc630
>
<(1+x) Handling our fault in a TRY at 0x00007fbebf5127d0>
<spurious rep/repne prefix @0x00007fbebe313df0 (f3 0f 1e fa): >
<Stopping application /home/merlijn/Desktop/brunotest/leak (23659)>
```

**Comment by derekbruening** [comment] 2018-08-28 15:52
a564eba made -no_vm_base_near_app on by default.  Closing.

**Closed by derekbruening** 2018-08-28 15:52 UTC
Labels: Bug-AppCrash, Hotlist-Release, OpSys-Linux

**Comment by derekbruening** [comment] 2018-08-28 18:04
Fix is in https://github.com/DynamoRIO/drmemory/releases/tag/release_2.0.1
