### ISSUE TITLE
Dr Memory crash when using opencv cv::medianBlur

### ISSUE THREAD

**Issue by JMVOLLE** [DynamoRIO/drmemory#1845] opened 2016-01-12 14:53 UTC
The following code crashes dr memory:

	cv::Mat Z = cv::Mat::zeros(16,16, CV_8UC1);
	cv::Mat out(16,16, CV_8UC1);
	cout << "1" << endl;
	cv::medianBlur(Z,out,3);
	cout << "2" << endl;

Crash log:
```
Dr. Memory internal crash at PC 0x7025d0a3.  Please report this at http://drmemory.org/issues.  Program aborted.
0xc0000005 0x00000000 0x7025d0a3 0x7025d0a3 0x00000001 0x00000000
Base: 0x701d0000
Registers: eax=0x00800027 ebx=0x00000000 ecx=0x00000000 edx=0x00000080
	esi=0x23441190 edi=0x00000000 esp=0x2343eddc ebp=0x702af8d8
	eflags=0x000
1.9.0-4-(Oct  2 2015 13:13:14) win61
-no_dynamic_options -disasm_mask 8 -logdir 'C:\Users\10133312\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\release\drmemorylib.dll;0;-visual_studio -logdir `C:\Users\10133312\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\10133312\AppData\Roaming\Dr. Memory\symcache` -lib_
0x702af8d8 0x00800027>
```

**Comment by derekbruening** [comment] 2016-02-04 22:41
Please try debug build and the various steps listed under "Narrowing Down the Source of the Problem" at https://github.com/DynamoRIO/drmemory/wiki/Debugging to obtain more information about whether this is limited to full mode, in light mode, in DynamoRIO, or where.

**Comment by derekbruening** [comment] 2016-03-05 21:05
I cannot reproduce this.

I downloaded
http://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.1.0/opencv-3.1.0.exe/download and compiled the sources with VS2013 to produce 32-bit libraries.

My entire program, containing your code:

```
#include "opencv2/core/mat.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include <iostream>

using namespace std;

int main(int argc, char** argv)
{
    cv::Mat Z = cv::Mat::zeros(16,16, CV_8UC1);
    cv::Mat out(16,16, CV_8UC1);
    cout << "1" << endl;
    cv::medianBlur(Z,out,3);
    cout << "2" << endl;
    return 0;
}
```

Build and run natively:

```
% cl /Zi /EHsc opencv.cpp /Id:/derek/extsw/opencv-3.1.0/opencv/build/include d:/derek/extsw/opencv-3.1.0/opencv/mybuild/lib/opencv_core310d.lib d:/derek/extsw/opencv-3.1.0/opencv/mybuild/lib/opencv_imgproc310d.lib

% PATH=~/extsw/opencv-3.1.0/opencv/mybuild/bin:$PATH ./opencv.exe
1
2
```

Run under Dr. Memory 1.9.0-4 on Windows 7:

```
% PATH=~/extsw/opencv-3.1.0/opencv/mybuild/bin:$PATH ~/drmemory/releases/DrMemory-Windows-1.9.0-4/bin/drmemory.exe -batch -- ./opencv.exe
~~Dr.M~~ Dr. Memory version 1.9.0
~~Dr.M~~ Running "./opencv.exe"
1
2
~~Dr.M~~ 
~~Dr.M~~ NO ERRORS FOUND:
```

What Windows version are you on?  What version of opencv is this?  Please also try debug build and the other steps listed above.

**Comment by derekbruening** [comment] 2016-03-05 21:09
```
04:06 PM ~/drmemory/releases/DrMemory-Windows-1.9.0-4
% bin/symquery -e dynamorio/lib32/release/dynamorio.dll -f -v -a `perl -e 'printf "0x%x\n", 0x7025d0a3 - 0x701d0000;'`
<debug info: type=PDB, has symbols, has line numbers>
instr_encode_arch+0x3f3
d:\drmemory_package\dynamorio\core\arch\x86\encode.c:2557+0x3
```

**Comment by derekbruening** [comment] 2016-03-25 14:56
Hearing no further information, we have to close this as we cannot reproduce and are not being supplied with any information, including basic info like versions.

**Closed by derekbruening** 2016-03-25 14:56 UTC
Labels: Bug-ToolCrash, Hotlist-Release, OpSys-Windows, Status-CannotReproduce, Status-NeedInfo
