### ISSUE TITLE
APP CRASH on AMD processor with no crash on Intel

### ISSUE THREAD

**Issue by avaneev** [DynamoRIO/drmemory#2233] opened 2019-11-05 12:06 UTC

**Comment by Carrotman42** [comment] 2019-11-05 14:16
Yes, it should afaik.

Please use this issue tracker for tracking known issues. I suggest posting to the user group (https://groups.google.com/forum/m/#!forum/DrMemory-Users) for just asking general questions. Also, I suggest supplying much more information about why it isn't "working" for you.

**Comment by avaneev** [comment] 2019-11-05 16:13
But it is a real issue - DR.memory crashes on Ryzen 3700x where it does not on Intel i7700k

**Comment by derekbruening** [comment] 2019-11-05 17:58
If this is meant to be a bug report, please provide actionable information: DrM version, OS version, a minimized reproducer, pasted output, etc.

**Comment by avaneev** [comment] 2019-11-06 06:39
DRM 2.2, OS Win10 1903, reproducing is complicated, there is no output from DRM, mainly crash of the application I run

**Comment by derekbruening** [comment] 2019-11-06 15:54
There's not much we can do without information on how to reproduce or at least precise details of what "crash" means (access violation in the application?  how do you know: is there a popup message, just an exit code, a console message, what??  be specific!  Is it an access violation in Dr. Memory with a Dr. Memory popup message?  assertion message?  you have not described any symptoms well enough...) along with logs.

**Comment by avaneev** [comment] 2019-11-07 07:03
When I open user interface window of an application, the DRM crashes like it is application crashing, this does not happen on i7700k

**Comment by Carrotman42** [comment] 2019-11-07 14:47
We cannot help without more information.

Think about it from our perspective: we have no information about your
problem except for what you've written down in this issue. But what you
have stated here has few specific details; for example, a "crash" can
happen in many different ways yet you have not described exactly what you
observe, and you haven't shown any logs to further describe the problem.

And without a minimal reproducer (small program you can share which
exhibits the problem) or without a way for us to reproduce on our own,
there isn't much we can actively do for you. The only thing we can do is
ask questions to try to get you to make progress.

Have you gone through the debugging steps found on this page? It should
help narrow down the problem: https://
github.com/DynamoRIO/drmemory/wiki/Debugging

**Comment by avaneev** [comment] 2019-11-07 16:43
Here is the 32-bit application that does not work on Ryzen 3700X:
https://www.voxengo.com/temp/r8brainPRO.rar
running as:
D:\TOOLS\DrMemory\bin\drmemory.exe -ignore_kernel -no_check_handle_leaks -no_count_leaks -no_possible_leaks -suppress D:\libvox\Utils\drmemory_suppress.txt --  "r8brain PRO.exe"

**Comment by Carrotman42** [comment] 2019-11-07 18:28
I do not personally own a Windows device that runs on a Ryzen processor. Sorry.

**Comment by derekbruening** [comment] 2019-11-08 15:40
It is very unlikely that the processor model plays any role here.  More likely it is some other difference between your two machines.  Please first determine basic things like whether it affects plain DynamoRIO and which modes of Dr. Memory by following the steps at  https://github.com/DynamoRIO/drmemory/wiki/Debugging#narrowing-down-the-source-of-the-problem and reporting the results.

**Comment by avaneev** [comment] 2019-11-09 10:14
I have two completely simiar Windows 10 machines, so the only difference is processor.

**Comment by kmar** [comment] 2020-01-10 17:05
I can confirm that Dr.Memory has problems on Ryzen, however in my case it's a 64-bit application and Dr.Memory thinks it's executing an invalid instruction,
however i do not see the instruction bytes in the debug log. my very wild guess is that maybe some library takes a different code path when it detects AMD/Ryzen?
```
drmemory -unaddr_only -v -debug -dr_debug EngineRuntime.exe
INFO: targeting application: "d:\mar\crabaware\CE4\_Data\Apps\CoonEd2\EngineRuntime.exe"
INFO: app cmdline: "EngineRuntime.exe"
INFO: launching frontend C:\Program Files (x86)\Dr. Memory\bin64\drmemory.exe to match target app bitwidth
INFO: waiting for other frontend...
INFO: targeting application: "d:\mar\crabaware\CE4\_Data\Apps\CoonEd2\EngineRuntime.exe"
INFO: app cmdline: "EngineRuntime.exe"
INFO: logdir is "C:\Users\k_mar\AppData\Roaming\Dr. Memory"
INFO: symcache_dir is "C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache"
INFO: Setting TZ to StINFO: DynamoRIO configuration directory is C:\Users\k_mar/dynamorio
INFO: configuring EngineRuntime.exe pid=8832 dr_ops="-disable_traces -bb_single_restore_prefix -max_bb_instrs 256 -vm_size 256M -no_enable_reset -no_vm_base_near_app -no_early_inject -logdir `C:\Users\k_mar\AppData\Roaming\Dr. Memory\dynamorio` "
INFO: configuring client "C:\Program Files (x86)\Dr. Memory\bin64\debug\drmemorylib.dll" ops="`-unaddr_only` -logdir `C:\Users\k_mar\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist `C:\WINDOWS*.d??,C:\Program Files\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 8832 "
INFO: waiting for app to exit...
~~Dr.M~~ Dr. Memory version 2.2.0
~~Dr.M~~ Running "EngineRuntime.exe"
~~Dr.M~~ Using system call file C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache\syscalls_x64.txt
<curiosity: rex.w on OPSZ_6_irex10_short4!>
<Application changing protections of system memory at least once (0x00007ffe9e3ba000-0x00007ffe9e3be000)>
<Invalid opcode encountered>
INFO: fetching symbols
INFO: should_fetch_symbols: modpath C:\WINDOWS\System32\KERNELBASE.dll => 0
INFO: should_fetch_symbols: modpath C:\Windows\System32\uxtheme.dll => 0
INFO: should_fetch_symbols: modpath C:\WINDOWS\SYSTEM32\ntdll.dll => 0
~~Dr.M~~ WARNING: application exited with abnormal code 0xc000001d

```
I still don't have a minimal repro in this case, but curiously enough a simple hello world commandline project in VS2017 makes Dr.Memory crash in 32-bit mode (64-bit mode works fine).
The output is then as follows:
```
drmemory -unaddr_only -v -debug -dr_debug drmem_crash_repro.exe
INFO: targeting application: "c:\Users\k_mar\source\repos\drmem_crash_repro\Release\drmem_crash_repro.exe"
INFO: app cmdline: "drmem_crash_repro.exe"
INFO: logdir is "C:\Users\k_mar\AppData\Roaming\Dr. Memory"
INFO: symcache_dir is "C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache"
INFO: Setting TZ to StINFO: DynamoRIO configuration directory is C:\Users\k_mar/dynamorio
INFO: configuring drmem_crash_repro.exe pid=26360 dr_ops="-disable_traces -bb_single_restore_prefix -max_bb_instrs 256 -vm_size 256M -no_enable_reset -no_vm_base_near_app -no_early_inject -logdir `C:\Users\k_mar\AppData\Roaming\Dr. Memory\dynamorio` "
INFO: configuring client "C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll" ops="`-unaddr_only` -logdir `C:\Users\k_mar\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist `C:\WINDOWS*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 26360 "
INFO: waiting for app to exit...
<Starting application c:\Users\k_mar\source\repos\drmem_crash_repro\Release\drmem_crash_repro.exe (26360)>
<Running on newer-than-this-build "Microsoft Windows 10-1903 x64">
<Early threads found>
<Initial options = -no_dynamic_options -logdir 'C:\Users\k_mar\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll;0;`-unaddr_only` -logdir `C:\Users\k_mar\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist `C:\WINDOWS*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 26360 ' -code_api -probe_api -stack_size 56K -disable_traces -no_enable_traces -max_elide_jmp 0 -max_elide_call 0 -no_shared_traces -bb_ibl_targets -bb_single_restore_prefix -no_shared_trace_ibl_routine -no_enable_reset -no_reset_at_switch_to_os_at_vmm_limit -reset_at_vmm_percent_free_limit 0 -no_reset_at_vmm_full -reset_at_commit_free_limit 0K -reset_every_nth_pending 0 -vm_size 262144K -no_vm_base_near_app -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr -pad_jmps_mark_no_trace >
~~Dr.M~~ Dr. Memory version 2.2.0
~~Dr.M~~ Running "drmem_crash_repro.exe"
~~Dr.M~~ Using system call file C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache\syscalls_wow64.txt
<Application c:\Users\k_mar\source\repos\drmem_crash_repro\Release\drmem_crash_repro.exe (26360).  Dr. Memory internal crash at PC 0x7bf1eb9b.  Please report this at http://drmemory.org/issues.  Program aborted.
0xc0000005 0x00000000 0x7bf1eb9b 0x7bf1eb9b 0x00000003 0x00000000
Base: 0x7bc10000
Registers: eax=0x00000000 ebx=0x001ff2bc ecx=0x9e2dde54 edx=0x00000000
        esi=0x247cc1a0 edi=0x249aefb8 esp=0x001ff2dc ebp=0x001ff310
        eflags=0x000
2.2.0-1-(Jul  1 2019 00:43:22) WinVer=105;Rel=1903;Build=18362;Edition=Core
-no_dynamic_options -logdir 'C:\Users\k_mar\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll;0;`-unaddr_only` -logdir `C:\Users\k_mar\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\k_mar\AppData\Roaming\Dr. Memory\symcache` -lib_blacklist `C:\WINDOWS*.d??
0x001ff310 0x7bea8a34
0x001ff334 0x7bea8eda
0x001ff854 0x7be9b977
0x001ff894 0x7bc1fe18
0x001ff8c8 0x7be81342
0x001ff934 0x7be81ac8>
INFO: fetching symbols
INFO: should_fetch_symbols: modpath C:\WINDOWS\System32\ucrtbase.dll => 0
INFO: should_fetch_symbols: modpath C:\WINDOWS\System32\KERNELBASE.dll => 0
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
```

the CPU is Ryzen 7 2700X 8-core, OS is Win10

this probably won't help much, but the problem that avaneev reported is real
if there's anything else I could do to help, please let me know

**Comment by Carrotman42** [comment] 2020-01-10 17:15
@kmar: it looks like the extra information about the invalid instruction should be in the thread-private log files, do you mind looking there and reporting what it says?

https://github.com/DynamoRIO/dynamorio/blob/1914d2d662345905d05bf4b99a94166c44f49b50/core/arch/x86/decode.c#L1257-L1273

**Comment by kmar** [comment] 2020-01-10 17:22
gladly, where can I find those thread-private log files? or do I have to build DynamoRIO in debug mode first? I'm having some issues to configure Dr.Memory using cmake, getting "dbghelp.dll required and not found"

**Comment by Carrotman42** [comment] 2020-01-10 19:22
The default distribution should include the code to write out per-thread files, no need to compile it yourself. (and as you probably realized, you are using "debug" mode due to the `-debug` flag you're passing to drmemory. (PS: thanks for providing reproducer command line!)

You will need to pass a higher verbosity flag to get those logs I linked to come out, though. `-loglevel 1` should be sufficient.

I actually don't remember where the log files come out off the top of my head, and it might be different given you're executing drmemory. The [docs](http://dynamorio.org/docs/using.html) (search for "loglevel" on that page) talk about a couple places, though you may be able to just pass `-logdir` to specify where you want the logs to end up.

**Comment by kmar** [comment] 2020-01-10 19:42
Hmm, I'm having problems to pass arguments to dynamorio through drmemory, tried -verbose 1 but that seems to only affect dr.memory. I still get only 1 log file, no information about the invalid instruction. There's no -loglevel in dr.memory's arguments, I guess this only applies to dynamorio (maybe I should try drrun?)

I managed to build 64-bit version of dr.memory, but cmake configures in reldbg by default.
I had less luck building a debug version, because cmake inserts extra "debug" folder to the path
and now I get dr_root errors.

Looking at the source, LOG is a macro that boils to nothing unless in debug mode or unless STANDALONE_DECODER s defined?

What is the correct way to setup a debug build via cmake please? I tried -DCMAKE_BUILD_TYPE=Debug and got the issues I mentioned with the extra subfolder.

**Comment by Carrotman42** [comment] 2020-01-10 20:00
I am thinking you don't need to recompile it: with the pre-built
distribution (which includes the debug build and release build already),
you could try running drmemory via 'drrun':  `drrun -t drmemory ` followed
by your other options (e.g. `-v -loglevel 1 -debug`, and others)

For building:

I'm assuming you found them because you're talking
about -DCMAKE_BUILD_TYPE=Debug, but just in case, the instructions for
building drmemory are on the wiki:
https://github.com/DynamoRIO/drmemory/wiki/How-To-Build

You are correct that LOG is turned into a no-op for the release build;
you're correct that you'll need to use debug mode to see it.

If you can manage to get it built, then I suppose you can just update the
source code to print out the information with a loglevel of just 0 (if the
debug build works), or just changing the relevant LOG messages to calls to
dr_fprintf (and moving the code out of the DODEBUG block, which also is
turned into a no-op for release builds)

**Comment by derekbruening** [comment] 2020-01-10 20:00
Go with the simplest reproducer: if the problem reproduces with plain DR,
run plain DR.  It is there in the DrMemory binary package (including debug
build binaries) as *dynamorio/bin64/drrun*, as shown in the docs such as
https://github.com/DynamoRIO/drmemory/wiki/Debugging#narrowing-down-the-source-of-the-problem.
(FTR, *-dr_ops "-loglevel 2" -dr_debug* is how to pass through the DrMemory
front-end.)  (For building follow
https://github.com/DynamoRIO/drmemory/wiki/How-To-Build.  If you had a
stale CMake config best to blow it away: maybe the problems you are hitting
are from switching major configs without a fresh directory.  It's hard to
say without seeing the full sequence of commands you ran.)

**Comment by kmar** [comment] 2020-01-10 20:04
Thanks, I'll try that and let you know.
In the meantime I quickly hacked in internal syslog and got this:
Invalid opcode @0x00007ffe9e2ebddf: 0xf0131, but I've no idea if it's legit. 0xf starting byte seems promising though

**Comment by kmar** [comment] 2020-01-10 20:39
I had little luck with -loglevel, passing args via dr_ops worked, but still no trace of thread logs.
I tried the simplest drrun: drrun -- app_name.exe and it ran without any problems.
running dr.memory directly or via drrun -t drmemory still complains about invalid instruction though

**Comment by kmar** [comment] 2020-01-10 21:29
byte-dumped version with 16 bytes of context before and 24 after the invalid instruction:
the sequence looks definitely like valid code, disassembly:
```
00000000: 448BDB                         mov          r11d,ebx
00000003: 4C8BD0                         mov          r10,rax
00000006: 4C03D8                         add          r11,rax
00000009: 498BC1                         mov          rax,r9
0000000C: 33C9                           xor          ecx,ecx
0000000E: 33D2                           xor          edx,edx
00000010: 0F01FA                         #UD
00000013: 418B01                         mov          eax,[r9]
00000016: 4184C5                         test         r13b,al
00000019: 7410                           jz           00000002B
0000001B: 418BCE                         mov          ecx,r14d
0000001E: 33C8                           xor          ecx,eax
00000020: F0410FB109                     lock cmpxchg [r9],ecx
00000025: 0F8438F7F6FF                   jz           0FFF6F763
```

**Comment by derekbruening** [comment] 2020-01-10 21:30
Where are you looking for the logs?  The DR logs are in dynamorio/logs as
it will tell you with -stderr_mask 15:

% dynamorio/bin64/drrun -debug -stderr_mask 15 -loglevel 2 --
d:/derek/dr/test/hello64.exe
<log
dir=D:\derek\drmemory\releases\DrMemory-Windows-2.2.0-1\dynamorio\logs\hello64.exe.11132.00000000>
<Starting application d:\derek\dr\test\hello64.exe (11132)>
...

**Comment by Carrotman42** [comment] 2020-01-10 21:43
Earlier you mentioned the instruction was "0xf0131", but in this latest
reply you have it as "0F01FA". With some online dissasembler I found, the
former is "lmsw word ptr [rcx]" (load machine status, a level 0 instruction
for OSes), but the latter does not seem to have a decoding.

Can you tell which one of these is correct, or does it change between runs?

Do you have the source to the application? What is it trying to do in
that block? Perhaps use a debugger to debug it to see what it says.

**Comment by kmar** [comment] 2020-01-10 21:47
the correct one is 0f01fa, which is monitorx. I found the code sequence in ntdll.dll in windows/system32

**Comment by Carrotman42** [comment] 2020-01-10 21:51
Interestingly enough, the online site I found says 0f01fa is invalid, but
says monitorx assembles to 0f01fa. Go figure.

**Comment by kmar** [comment] 2020-01-10 21:54
please see here, page 205
https://www.amd.com/system/files/TechDocs/24594.pdf
monitorx is probably some AMD extension
so what happens:

ntdll examines CPUID and detects the presence of monitorx, this doesn't happen on Intel but does happen on Ryzen
so ntdll takes a path where it uses monitorx which causes dynamoRIO to detect an "invalid opcode"
one question remains: how to solve this problem?

**Comment by Carrotman42** [comment] 2020-01-10 22:28
I imagine the solution is to add the opcode to our decoder. I am not sure
how DR handles AMD- (or Intel-specific-) opcodes, but I hope it's unlikely
for Intel to use this opcode as something else in the future.

The decoder is in a few parts, but you probably want to look at these three
files:
*
https://github.com/DynamoRIO/dynamorio/blob/master/core/arch/x86/decode_table.c
* https://github.com/DynamoRIO/dynamorio/blob/master/core/arch/x86/decode.c
*
https://github.com/DynamoRIO/dynamorio/blob/master/core/arch/x86/decode_fast.c

Unfortunately I have not added an opcode before, so I'm not quite sure how
to do it. I suggest looking at some previous commits to those files to
learn more about how it works.

**Comment by kmar** [comment] 2020-01-10 23:01
it seems to work :) unaddr_only seems fine, now trying full but that's quite slow, still waiting for the app to start
would you prefer a PR or would a patch suffice? I only modified two files (decode_table.c and opcodes.h) in dynamoRIO

**Comment by kmar** [comment] 2020-01-10 23:38
here's the patch if it suffices this way (I couldn't upload the .patch file here, sorry):
```
From e947406acf23fdafddff9ddc5d85c9e8de7de28b Mon Sep 17 00:00:00 2001
From: kmar <k_mar@seznam.cz>
Date: Sat, 11 Jan 2020 00:14:36 +0100
Subject: [PATCH] add support for AMD's monitorx and mwaitx to fix issues on
 Ryzen

---
 core/arch/x86/decode_table.c | 7 ++++++-
 core/arch/x86/opcode.h       | 4 ++++
 2 files changed, 10 insertions(+), 1 deletion(-)

diff --git a/core/arch/x86/decode_table.c b/core/arch/x86/decode_table.c
index 865c3ef9..ccbb1996 100644
--- a/core/arch/x86/decode_table.c
+++ b/core/arch/x86/decode_table.c
@@ -1594,6 +1594,10 @@ const instr_info_t * const op_instr[] =
 
     /* Intel PT extensions */
     /* OP_ptwrite         */ &prefix_extensions[188][1],
+
+   /* AMD monitor extensions */
+   /* OP_monitorx      */   &rm_extensions[2][2],
+   /* OP_mwaitx        */   &rm_extensions[2][3],
 };
 
 
@@ -6559,7 +6563,8 @@ const instr_info_t rm_extensions[][8] = {
   { /* rm extension 2 */
     {OP_swapgs, 0xf80f0177, "swapgs", xx, xx, xx, xx, xx, mrm|o64, x, END_LIST},
     {OP_rdtscp, 0xf90f0177, "rdtscp", edx, eax, xx, xx, xx, mrm|xop, x, exop[10]},/*AMD-only*/
-    {INVALID,   0x0f0131, "(bad)", xx, xx, xx, xx, xx, no, x, NA},
+    {OP_monitorx, 0x0f01fa, "monitorx",  xx, xx, eax, ecx, edx, mrm, x, END_LIST},/*AMD-only*/
+    {OP_mwaitx, 0x0f01fb, "mwaitx",  xx, xx, eax, ecx, xx, mrm, x, END_LIST},/*AMD-only*/
     {INVALID,   0x0f0131, "(bad)", xx, xx, xx, xx, xx, no, x, NA},
     {INVALID,   0x0f0131, "(bad)", xx, xx, xx, xx, xx, no, x, NA},
     {INVALID,   0x0f0131, "(bad)", xx, xx, xx, xx, xx, no, x, NA},
diff --git a/core/arch/x86/opcode.h b/core/arch/x86/opcode.h
index 70de447e..b71628d4 100644
--- a/core/arch/x86/opcode.h
+++ b/core/arch/x86/opcode.h
@@ -1591,6 +1591,10 @@ enum {
     /* Intel PT extensions */
     /* 1417 */ OP_ptwrite, /**< IA-32/AMD64 PT OP_ptwrite opcode. */
 
+    /* AMD monitor extensions */
+    /* 1418 */ OP_monitorx,  /**< AMD64 monitorx opcode. */
+    /* 1419 */ OP_mwaitx,    /**< AMD64 mwaitx opcode. */
+
     OP_AFTER_LAST,
     OP_FIRST = OP_add,           /**< First real opcode. */
     OP_LAST = OP_AFTER_LAST - 1, /**< Last real opcode. */
-- 
2.21.0.windows.1
 
```

**Comment by derekbruening** [comment] 2020-01-11 01:47
Thank you for the partial patch -- however, as the comment at the top of
the opcode enum states, 7 different places (listed there) need to be
updated.  We would love to have a DR issue
<https://github.com/DynamoRIO/dynamorio/issues> filed and a pull request
submitted.

**Comment by kmar** [comment] 2020-01-11 03:45
oh I know how this ends, I've been down this road before :)

just to be clear:
point 1&2 is what I already did
point 3: running the perl script didn't produce any changes so I guess it's only used for renumbering (I simply added two new opcodes at the end)
point 4 seems obsolete since there's already OP_AFTER_LAST at the end and OP_LAST = OP_AFTER_LAST-1
point 5 (decode_fast tables) doesn't have to be changed in this case from what I understand
point 6 (since there are no INSTR_CREATE macros for the original SSE monitor/mwait, I assume I don't have to add anything either)
as for point 7, I can modify the suite (ir_x86_0args.h), but how do I build and run it?

I'll try to create a PR and let you know. I assume you'd prefer a separate branch for the PR?

Thank You and @Carrotman42 for guiding me through this whole process.

**Comment by kmar** [comment] 2020-01-11 08:44
the issue can be found here, I didn't know how to link PR to a specific issue so I linked in comments
https://github.com/DynamoRIO/dynamorio/issues/4011

**Comment by kmar** [comment] 2020-01-11 09:27
I was wrong about point 6, the tests fail when I try to add INSTR_CREATE for monitorx and mwaitx, complaining about opcode size. these are simple 3-byte instructions, what is the correct way of defining these? I thought the size will be deduced automatically from op_instr... what am I missing?

**Comment by derekbruening** [comment] 2020-01-11 21:16
On Fri, Jan 10, 2020 at 10:45 PM kmar <notifications@github.com> wrote:

> oh I know how this ends, I've been down this road before :)
>
> just to be clear:
> point 1&2 is what I already did
> point 3: running the perl script didn't produce any changes so I guess
> it's only used for renumbering (I simply added two new opcodes at the end)
> point 4 seems obsolete since there's already OP_AFTER_LAST at the end and
> OP_LAST = OP_AFTER_LAST-1
> point 5 (decode_fast tables) doesn't have to be changed in this case from
> what I understand
> point 6 (since there are no INSTR_CREATE macros for the original SSE
> monitor/mwait, I assume I don't have to add anything either)
>
INSTR_CREATE_monitor and _mwait do exist.


> as for point 7, I can modify the suite (ir_x86_0args.h), but how do I
> build and run it?
>
The wiki documents how to build tests and how to use ctest:
https://github.com/DynamoRIO/dynamorio/wiki/Test-Suite


> I'll try to create a PR and let you know. I assume you'd prefer a separate
> branch for the PR?
>
As explained in https://github.com/DynamoRIO/dynamorio/wiki/Workflow pull
requests originating in the official repo always use separate branches.

**Comment by derekbruening** [comment] 2020-01-11 21:17
Do you mean operand size?  Seeing the precise output may help.

**Comment by derekbruening** [comment] 2020-01-11 21:20
On Sat, Jan 11, 2020 at 3:44 AM kmar <notifications@github.com> wrote:

> the issue can be found here, I didn't know how to link PR to a specific
> issue so I linked in comments
>

The commit message has the link when following the requested conventions:
https://github.com/DynamoRIO/dynamorio/wiki/Code-Reviews

**Comment by kmar** [comment] 2020-01-12 06:10
ok, I've already sorted things out. build including relevant tests passes (AArch64 precommit didn't even start, I don't know if that's normal, but I didn't change anything related to ARM so I don't expect any problems) so all I can do now is wait for review

the PR is here https://github.com/DynamoRIO/dynamorio/pull/4012

**Comment by kmar** [comment] 2020-01-13 23:43
so, now that the fix has been merged into the master of dynamorio (hurray), can we expect a hotfix release (or cronbuild) of drmemory anytime soon? (I understand that a release of dynamorio has to come out first)
it would be much appreciated, thanks!

**Comment by derekbruening** [comment] 2020-01-13 23:53
Dr. Memory just needs its DR submodule updated and then the next cronbuild will have the fix: https://github.com/DynamoRIO/drmemory/wiki/UpdatingDR

**Comment by derekbruening** [comment] 2020-01-16 23:05
I tried to update DR but the change to use override and require C++11 breaks some Dr. Memory code so there is more work to be done.  I don't know when I will have time for that so if someone wants to volunteer to fix it that will help.

**Closed** 2020-01-19 04:19 UTC
Labels: Bug-AppCrash
