### ISSUE TITLE
Support Windows 10 versions [drsyscall]

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/drmemory#2186] opened 2019-04-02 12:30 UTC
The last supported version is 1803 (drsyscall_os_init).
What is the problem of support other version? (1809)

If the problem is to get a Windows version: >>

`winver` tool (x:\windows\system32\winver.exe) uses registry values under HKLM\...\CurrentVersion to get a version and build number.

![43fdsf](https://user-images.githubusercontent.com/49196211/55402387-e3d37780-5542-11e9-9597-8ba8ef3412fe.PNG)
![fsd](https://user-images.githubusercontent.com/49196211/55402389-e3d37780-5542-11e9-9574-6d92e58b4b9d.PNG)
![ded](https://user-images.githubusercontent.com/49196211/55402391-e3d37780-5542-11e9-9cce-318487d4465f.png)

**Comment by derekbruening** [comment] 2019-04-02 14:17
Duplicate of #2126, which is de-prioritized due to #1848, which is present in the 2.1.0 release and supports 1809 via auto-generating syscall numbers.

**Comment by derekbruening** [comment] 2019-04-02 14:21
Just saw the `[drsyscall]` in the title: drsyscall needs to switch to using auto-generated syscall number files which is #1983.  If you'd like to contribute to that effort it would be much appreciated.

**Comment by derekbruening** [comment] 2019-04-02 14:23
Closing; duplicate of #1983.

**Closed by derekbruening** 2019-04-02 14:23 UTC
Labels: Status-Duplicate
