### ISSUE TITLE
"Latest Build" link broken

### ISSUE THREAD

**Issue by fidget324** [DynamoRIO/drmemory#2075] opened 2018-02-11 00:02 UTC
On this page: https://github.com/DynamoRIO/drmemory/wiki/Latest-Build
the http://build.chromium.org/p/client.drmemory/builds/
is giving a 404.

**Comment by derekbruening** [comment] 2018-02-11 00:25
Duplicate of #2062

**Closed by derekbruening** 2018-02-11 00:25 UTC
Labels: Status-Duplicate

**Comment by fidget324** [comment] 2018-02-11 01:24
So if I need a trunk build for Wndows (e.g. to address DynamoRIO [#2666](https://github.com/DynamoRIO/dynamorio/issues/2666)), is the only solution for me to build the trunk from sources?

**Comment by derekbruening** [comment] 2018-03-06 15:13
There are now weekly "cronbuilds" at https://github.com/DynamoRIO/drmemory/releases

**Comment by fidget324** [comment] 2018-03-13 18:18
Question: I have a Dynamo client which also uses the Dr. Fuzz extension. I downloaded the DynamoRIO and Dr. Memory weekly release builds and pointed my client to both of them (by including them as CMake modules, as I had done before with the 7.0.0-RC1 release). Now my client is giving the error:
```
Unable to load client library: drfuzz.dll
  Cannot find library.
```
which I was not getting before with the 7.0.0-RC1 installation.

Any pointers?
