### ISSUE TITLE
Drmemory cannot run the Win32 "net" ("C:\Windows\system32\net.exe") utility

### ISSUE THREAD

**Issue by gisburn** [DynamoRIO/drmemory#2503] opened 2024-07-16 15:15 UTC
**Describe the bug**
Plain, Win10/64bit, fresh DrMemory 2.6 installation.

DrMemory crashes while trying to run the "net.exe" utility.

Example:
```
drmemory -- C:\Windows\system32\net.exe
<Application C:\Windows\SysWOW64\net.exe (9904).  Dr. Memory internal crash at PC 0x03180d72.  Please report this at http://drmemory.org/issues along with the results of running '-debug -dr_debug'.  Program aborted.
0xc06d007f 0x00000000 0x03180d72 0x03180d72 0x0290f344 0x00000000
Base: 0x728d0000
Registers: eax=0x0290f2c8 ebx=0x00000000 ecx=0x00000001 edx=0x00000000
        esi=0x03040000 edi=0x00000000 esp=0x0290f2c8 ebp=0x0290f320
        eflags=0x000
2.6.0-0-(Sep 21 2023 17:48:48) WinVer=105;Rel=2009;Build=19045;Edition=Enterprise
-no_dynamic_options -logdir 'C:\Users\roland_mainz\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\release\drmemorylib.dll;0;-logdir `C:\Users\roland_mainz\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\roland_mainz\AppData\Roaming\Dr. Memory\symcache` -lib_blocklist_default
0x0290f320 0x724f23de
0x0290f378 0x724f3b4c
0x0290f3d4 0x7248c593
0x0290f400 0x724d4d37
0x0290f434 0x724acf0f
0x0290f44c 0x724ae079
0x0290f6c8 0x724ae23e
0x0290f6e8 0x73889423
0x72a055f8 0x73800000
0x73800000 0x00000003>
~~Dr.M~~ WARNING: unable to locate results file: can't open C:\Users\roland_mainz\AppData\Roaming\Dr. Memory/resfile.9904 (code=2).
Dr. Memory failed to start the target application, perhaps due to
interference from invasive security software.
Try disabling other software or running in a virtual machine.
WARNING: Examine the following unusual libraries in this process to help identify
invasive software that may have affected the target application:

        C:\Windows\System32\bcrypt.dll

Please file a bug about this at http://drmemory.org/issues
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff


```

**Comment by gisburn** [comment] 2024-10-07 22:15
I tried again with the newest weekly build and debug options, and got this failure:
---- snip ----
```
"C:\Program Files (x86)\Dr. Memory\bin\drmemory.exe" -debug -dr_debug -- net use
<Starting application C:\Windows\SysWOW64\net.exe (14264)>
<Running on newer-than-this-build "Microsoft Windows 10-2009 x64">
<Early threads found>
<Initial options = -no_dynamic_options -logdir 'C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll;0;-logdir `C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory\symcache` -lib_blocklist_default `C:\Windows*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 14264 ' -client_lib32 'C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll;0;-logdir `C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory\symcache` -lib_blocklist_default `C:\Windows*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 14264 ' -code_api -probe_api -stack_size 56K -disable_traces -no_enable_traces -max_elide_jmp 0 -max_elide_call 0 -no_shared_traces -bb_ibl_targets -bb_single_restore_prefix -no_shared_trace_ibl_routine -no_enable_reset -no_reset_at_switch_to_os_at_vmm_limit -reset_at_vmm_percent_free_limit 0 -no_reset_at_vmm_full -reset_at_commit_free_limit 0B -reset_every_nth_pending 0 -vm_size 256M -no_early_inject -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr >
<ignoring failure of private library KERNELBASE.dll entry (call reason=1)
>
<Application C:\Windows\SysWOW64\net.exe (14264).  Internal Error: DynamoRIO debug check failure: D:\a\drmemory\drmemory\dynamorio\core\win32\loader.c:777 !is_dynamo_address(dcontext->app_fls_data)
(Error occurred @0 frags in tid 16244)
2.6.20000-0-(Oct  5 2024 03:01:59) WinVer=105;Rel=2009;Build=19045;Edition=Enterprise
-no_dynamic_options -logdir 'C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory\dynamorio' -client_lib 'C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll;0;-logdir `C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory` -symcache_dir `C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory\symcache` -lib_blocklist_default `C:\W
0x1b741ed4 0x6387dfa9
0x1b74200c 0x63acbba2
0x1b742078 0x63ac6043
0x1b74208c 0x63a8683f
0x1b74261c 0x63a86be2
0x1b742678 0x63a88166
0x1b742d64 0x63c20016
0x02b8e768 0x636723de
0x02b8e7c0 0x63673b4c
0x02b8e81c 0x6360c593
0x02b8e848 0x63654d37
0x02b8e87c 0x6362cf0f
0x02b8e894 0x6362e079
0x02b8eb10 0x6362e23e
0x02b8eb30 0x73b03832
C:\Program Files (x86)\Dr. Memory\dynamorio\lib32\debug\dynamorio.dll=0x637b0000
C:\Windows/system32/RPCRT4.dll=0x03260000
C:\Program Files (x86)\Dr. Memory\bin\debug\drmemorylib.dll=0x73800000
C:\Program Files (x86)\Dr. Memory\bin\debug/dbghelp.dll=0x635e0000
C:\Windows/system32/ucrtbase.dll=0x03330000
C:\Windows/system32/kernel32.dll=0x034d0000
C:\Windows/system32/KERNELBASE.dll=0x035c0000>
~~Dr.M~~ WARNING: unable to locate results file: can't open C:\Users\RFW_Antrano\AppData\Roaming\Dr. Memory/resfile.14264 (code=2).
Dr. Memory failed to start the target application, perhaps due to
interference from invasive security software.
Try disabling other software or running in a virtual machine.
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
```
---- snip ----

@derekbruening Does this look like a variation of bug #7024 to you ?

**Comment by derekbruening** [comment] 2024-10-08 15:59
No, the FLS assert makes it look like a duplicate of https://github.com/DynamoRIO/drmemory/issues/2456. Some DynamoRIO issue with handling FLS (fiber-local-storage) in private libraries. Closing as duplicate to consolidate under https://github.com/DynamoRIO/drmemory/issues/2456.

**Closed by derekbruening** 2024-10-08 15:59 UTC
