### ISSUE TITLE
Dr memory internal crash at PC 0x00000000710cbc4b

### ISSUE THREAD

**Issue by etcjiang** [DynamoRIO/drmemory#2315] opened 2020-10-08 05:36 UTC
```
E:\ backup>drmemory main.exe -debug -dr_debug
~~Dr.M~~ Dr. Memory version 2.3.0
~~Dr.M~~ Running "main.exe -debug -dr_debug"
~~Dr.M~~ Using system call file C:\Users\etcjiang\AppData\Roaming\Dr. Memory\symcache\syscalls_x64.txt
~~Dr.M~~
~~Dr.M~~ Error #1: UNADDRESSABLE ACCESS beyond top of stack: reading 0x0000000000aafbf0-0x0000000000aafbf8 8 byte(s)
~~Dr.M~~ # 0 ___chkstk_ms                            [../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm:153]
~~Dr.M~~ # 1 _pei386_runtime_relocator               [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/pseudo-reloc.c:460]
~~Dr.M~~ # 2 __tmainCRTStartup                       [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:261]
~~Dr.M~~ # 3 .l_start                                [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:193]
~~Dr.M~~ # 4 KERNEL32.dll!BaseThreadInitThunk
~~Dr.M~~ Note: @0:00:00.188 in thread 3300
~~Dr.M~~ Note: 0x0000000000aafbf0 refers to 424 byte(s) beyond the top of the stack 0x0000000000aafd98
~~Dr.M~~ Note: instruction: or     $0x0000000000000000 (%rcx) -> (%rcx)
~~Dr.M~~
~~Dr.M~~ Error #2: UNADDRESSABLE ACCESS beyond top of stack: reading 0x0000000000aafb90-0x0000000000aafb98 8 byte(s)
~~Dr.M~~ # 0 ___chkstk_ms                        [../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm:153]
~~Dr.M~~ # 1 __shmem_grab                        [../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/shmem-win32.c:54]
~~Dr.M~~ # 2 _Unwind_SjLj_Register               [../../../../src/gcc-4.6.1/libgcc/../gcc/unwind-sjlj.c:128]
~~Dr.M~~ # 3 _GLOBAL__sub_I_main                 [E:/ backup/main.cpp:231]
~~Dr.M~~ # 4 __do_global_ctors                   [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/gccmain.c:44]
~~Dr.M~~ # 5 __tmainCRTStartup                   [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:299]
~~Dr.M~~ # 6 .l_start                            [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:193]
~~Dr.M~~ # 7 KERNEL32.dll!BaseThreadInitThunk
~~Dr.M~~ Note: @0:00:00.320 in thread 3300
~~Dr.M~~ Note: 0x0000000000aafb90 refers to 88 byte(s) beyond the top of the stack 0x0000000000aafbe8
~~Dr.M~~ Note: instruction: or     $0x0000000000000000 (%rcx) -> (%rcx)
~~Dr.M~~
~~Dr.M~~ Error #3: UNADDRESSABLE ACCESS beyond top of stack: reading 0x0000000000aafb50-0x0000000000aafb58 8 byte(s)
~~Dr.M~~ # 0 ___chkstk_ms                      [../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm:153]
~~Dr.M~~ # 1 __shmem_grab                      [../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/shmem-win32.c:54]
~~Dr.M~~ # 2 fc_key_init_once                  [../../../../src/gcc-4.6.1/libgcc/../gcc/unwind-sjlj.c:119]
~~Dr.M~~ # 3 _GLOBAL__sub_I_main               [E:/ backup/main.cpp:231]
~~Dr.M~~ # 4 __do_global_ctors                 [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/gccmain.c:44]
~~Dr.M~~ # 5 __tmainCRTStartup                 [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:299]
~~Dr.M~~ # 6 .l_start                          [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:193]
~~Dr.M~~ # 7 KERNEL32.dll!BaseThreadInitThunk
~~Dr.M~~ Note: @0:00:00.422 in thread 3300
~~Dr.M~~ Note: 0x0000000000aafb50 refers to 88 byte(s) beyond the top of the stack 0x0000000000aafba8
~~Dr.M~~ Note: instruction: or     $0x0000000000000000 (%rcx) -> (%rcx)
~~Dr.M~~
~~Dr.M~~ Error #4: UNADDRESSABLE ACCESS beyond top of stack: reading 0x0000000000aafb50-0x0000000000aafb58 8 byte(s)
~~Dr.M~~ # 0 ___chkstk_ms                      [../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm:153]
~~Dr.M~~ # 1 __shmem_grab                      [../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/shmem-win32.c:54]
~~Dr.M~~ # 2 fc_key_init_once                  [../../../../src/gcc-4.6.1/libgcc/../gcc/unwind-sjlj.c:111]
~~Dr.M~~ # 3 _GLOBAL__sub_I_main               [E:/ backup/main.cpp:231]
~~Dr.M~~ # 4 __do_global_ctors                 [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/gccmain.c:44]
~~Dr.M~~ # 5 __tmainCRTStartup                 [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:299]
~~Dr.M~~ # 6 .l_start                          [c:/crossdev/src/mingw-w64-svn/mingw-w64-crt/crt/crtexe.c:193]
~~Dr.M~~ # 7 KERNEL32.dll!BaseThreadInitThunk
~~Dr.M~~ Note: @0:00:00.450 in thread 3300
~~Dr.M~~ Note: 0x0000000000aafb50 refers to 88 byte(s) beyond the top of the stack 0x0000000000aafba8
~~Dr.M~~ Note: instruction: or     $0x0000000000000000 (%rcx) -> (%rcx)
Assertion failed!

Program: E:\ backup\main.exe
File: E:/ backup/main.cpp, Line 190

Expression: num > 0
~~Dr.M~~
~~Dr.M~~ ERRORS FOUND:
~~Dr.M~~       4 unique,     8 total unaddressable access(es)
~~Dr.M~~       0 unique,     0 total uninitialized access(es)
~~Dr.M~~       0 unique,     0 total invalid heap argument(s)
~~Dr.M~~       0 unique,     0 total GDI usage error(s)
~~Dr.M~~       0 unique,     0 total handle leak(s)
~~Dr.M~~       0 unique,     0 total warning(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of leak(s)
~~Dr.M~~       0 unique,     0 total,      0 byte(s) of possible leak(s)
~~Dr.M~~ ERRORS IGNORED:
~~Dr.M~~       3 potential error(s) (suspected false positives)
~~Dr.M~~          (details: C:\Users\etcjiang\AppData\Roaming\Dr. Memory\DrMemory-main.exe.3240.000\potential_errors.txt)
~~Dr.M~~      15 unique,    17 total,  14256 byte(s) of still-reachable allocation(s)
~~Dr.M~~          (re-run with "-show_reachable" for details)
~~Dr.M~~ Details: C:\Users\etcjiang\AppData\Roaming\Dr. Memory\DrMemory-main.exe.3240.000\results.txt
~~Dr.M~~ WARNING: application exited with abnormal code 0x3

E:\ backup>
```

**Comment by derekbruening** [comment] 2020-10-08 18:07
I don't see any "internal crash" as in the title.  I only see reports about chkstk, which does indeed touch beyond the top of the stack, and is normally auto-suppressed by pattern matching.  Given the MinGW CRT there this is probably a duplicate of #2248.

**Closed by derekbruening** 2020-10-08 18:07 UTC
