### ISSUE TITLE
ASSERT FAILURE: D:\drmemory_package\drstrace\drstrace.c:670: false (drsys failed to init) `

### ISSUE THREAD

**Issue by Robert-M-Muench** [DynamoRIO/drmemory#2209] opened 2019-07-03 15:37 UTC
````
...elop\rm-asset\nlpp\release> drstrace -- .\nlpp_debug_3.5.0.9.exe
ASSERT FAILURE: D:\drmemory_package\drstrace\drstrace.c:670: false (drsys failed to init)
````

**Comment by Carrotman42** [comment] 2019-07-03 16:20
Can you give a little more context to your problem? What is nlpp_debug_3.5.0.9.exe? What system are you running on?

I looked through the drstrace code and unfortunately the error details seem to be dropped and there's no option to have them printed out, which is unfortunate, but you could always step through with a debugger to see what exactly is failing. With that information we could help you make more progress. Alternatively you could change the code locally to print out more information when there's a failure (and maybe send it in as a PR so that the next person to encounter this problem will have an easier time debugging).

**Comment by Robert-M-Muench** [comment] 2019-07-03 17:40
nlpp_debug_3.5.0.9.exe is an application we develop. So, what do you want to know about it? This is running on Windows: WinVer=105;Rel=1903;Build=18362;Edition=Core

I  haven't build drstrace myself (yet) so, I think running it through the debugger won't help.

I'm not sure if I can get into the codebase quick enough to know what to print... Since it's an assertion that fails, I thought this already gives a good hint about the root cause of the problem.

**Comment by derekbruening** [comment] 2019-07-03 21:37
This bug filing implies that this problem *only* happens with your particular `nlpp_debug_3.5.0.9.exe` application (normally you'd go try hello,world or sthg else tiny that you could share before filing a bug, and if that also failed, you'd put that as the app in the bug: standard problem minimization), which is why we're asking about that application and suggesting that you investigate it, because on the surface only those with access to that application could look into it.  That said (please take that into account for future bug filings), this is almost certainly a duplicate of the general issue of having drstrace auto-update for new versions of Windows: #1983.  Marking as a duplicate.

**Closed by derekbruening** 2019-07-03 21:37 UTC
