### ISSUE TITLE
Dr. Memory Internal Crash

### ISSUE THREAD

**Issue by garminuser** [DynamoRIO/drmemory#2145] opened 2019-01-08 18:53 UTC
Running Dr. Memory from within Visual Studio 2015 generated a crash.

No memory issues prior to the crash.  Is it possible to know the reason for this error?

![image](https://user-images.githubusercontent.com/46496561/50852043-bd36e380-133b-11e9-8b67-21bd893f49f7.png)

**Comment by derekbruening** [comment] 2019-03-10 19:00
Making the crash address text so it's searchable: 0x7381c707
Matches #2096 so I'm going to mark as a duplicate of that issue.

Please try a more recent cronbuild: https://github.com/DynamoRIO/drmemory/releases/latest
Please try the standard diagnostic steps at
https://github.com/DynamoRIO/drmemory/wiki/Debugging#general-tips and
https://github.com/DynamoRIO/drmemory/wiki/Debugging#narrowing-down-the-source-of-the-problem
and report the results in #2096.

**Closed by derekbruening** 2019-03-10 19:00 UTC
Labels: Bug-ToolCrash, Status-Duplicate
