### ISSUE TITLE
Internal crash at PC 0x09ed0d72

### ISSUE THREAD

**Issue by fpailler** [DynamoRIO/drmemory#2506] opened 2024-08-14 09:52 UTC
When i'm trying to run DrMemory on my 32bit Windows application the message below appear.
```
<Application C:\Users\fpailler\Documents\TestApp\Debug\TestApp.exe (24664).  Dr. Memory internal crash at PC 0x02b70d72.  Please report this at http://drmemory.org/issues along with the results of running '-debug -dr_debug'.  Program aborted.
0xc06d007f 0x00000000 0x02b70d72 0x02b70d72 0x008ff068 0x00000000
Base: 0x5c130000
Registers: eax=0x008fefe8 ebx=0x00000000 ecx=0x00000001 edx=0x00000000
        esi=0x02a30000 edi=0x00000000 esp=0x008fefe8 ebp=0x008ff044
        eflags=0x000
2.6.0-0-(Sep 21 2023 17:48:48) WinVer=105;Rel=2009;Build=19045;Edition=Enterprise
-no_dynamic_options -logdir 'C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs\dynamorio' -client_lib 'C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\bin\release\drmemorylib.dll;0;-logdir `C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs` -symcache_dir `
```

The command line used to produice the issue is : `C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\bin> .\drmemory.exe -- C:\Users\fpailler\Documents\TestApp\Debug\TestApp.exe`

I tried on over application I'm working on and with 32bit DrMemory binary and it's the same issue for all.

So I run the command line `.\drmemory.exe -debug -dr_debug -- C:\Users\fpailler\Documents\TestApp\Debug\TestApp.exe` to get more information. The output is :
```
<Starting application C:\Users\fpailler\Documents\TestApp\Debug\TestApp.exe (20032)>
<Running on newer-than-this-build "Microsoft Windows 10-2009 x64">
<Early threads found>
<Initial options = -no_dynamic_options -logdir 'C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs\dynamorio' -client_lib 'C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\bin\debug\drmemorylib.dll;0;-logdir `C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs` -symcache_dir `C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs\symcache` -lib_blocklist_default `C:\Windows*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 20032 ' -client_lib32 'C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\bin\debug\drmemorylib.dll;0;-logdir `C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs` -symcache_dir `C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs\symcache` -lib_blocklist_default `C:\Windows*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??,C:\Program Files (x86)\Common Files\Microsoft Shared*.d??` -resfile 20032 ' -code_api -probe_api -stack_size 56K -disable_traces -no_enable_traces -max_elide_jmp 0 -max_elide_call 0 -no_shared_traces -bb_ibl_targets -bb_single_restore_prefix -no_shared_trace_ibl_routine -no_enable_reset -no_reset_at_switch_to_os_at_vmm_limit -reset_at_vmm_percent_free_limit 0 -no_reset_at_vmm_full -reset_at_commit_free_limit 0B -reset_every_nth_pending 0 -vm_size 256M -no_early_inject -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr >
<Application C:\Users\fpailler\Documents\TestApp\Debug\TestApp.exe (20032).  Internal Error: DynamoRIO debug check failure: D:\a\drmemory\drmemory\dynamorio\core\win32\loader.c:775 !is_dynamo_address(dcontext->app_fls_data)
(Error occurred @0 frags in tid 25112)
2.6.0-0-(Sep 21 2023 17:54:43) WinVer=105;Rel=2009;Build=19045;Edition=Enterprise
-no_dynamic_options -logdir 'C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs\dynamorio' -client_lib 'C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\bin\debug\drmemorylib.dll;0;-logdir `C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs` -symcache_dir `C:\Users\fpailler\Applicat
0x23c71ed4 0x5be9df39
0x23c7200c 0x5c0eab12
0x23c72078 0x5c0e4f43
0x23c7208c 0x5c0a56df
0x23c7261c 0x5c0a5a82
0x23c72678 0x5c0a7006
0x23c72d64 0x5c238016
0x0056e870 0x5bb123de
0x0056e8c8 0x5bb13b4c
0x0056e924 0x5baac593
0x0056e950 0x5baf4d37
0x0056e984 0x5baccf0f
0x0056e99c 0x5bace079
0x0056ec18 0x5bace23e
0x0056ec38 0x73b035b2
C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\dynamorio\lib32\debug\dynamorio.dll=0x5bdd0000
C:\Windows/system32/RPCRT4.dll=0x02630000
C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\bin\debug\drmemorylib.dll=0x73800000
C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\bin\debug/dbghelp.dll=0x5ba80000
C:\Windows/system32/ucrtbase.dll=0x02700000
C:\Windows/system32/kernel32.dll=0x02900000
C:\Windows/system32/KERNELBASE.dll=0x029>
~~Dr.M~~ WARNING: unable to locate results file: can't open C:\Users\fpailler\Applications\DrMemory-Windows-2.6.0\drmemory\logs/resfile.20032 (code=2).
Dr. Memory failed to start the target application, perhaps due to
interference from invasive security software.
Try disabling other software or running in a virtual machine.
WARNING: Examine the following unusual libraries in this process to help identify
invasive software that may have affected the target application:

        C:\Windows\SYSTEM32\USERENV.dll
        C:\Windows\SYSTEM32\privman32.dll
        C:\Windows\System32\gdi32full.dll
        C:\Windows\System32\msvcp_win.dll
        C:\Windows\System32\IMM32.DLL
        C:\Windows\System32\win32u.dll
        C:\Windows\System32\SHLWAPI.dll
        C:\Windows\System32\ole32.dll
        C:\Windows\System32\bcrypt.dll
        C:\Windows\System32\combase.dll

Please file a bug about this at http://drmemory.org/issues
~~Dr.M~~ WARNING: application exited with abnormal code 0xffffffff
```

Using "-light" option doesn't solved the issue.
Using "-leaks_only -no_count_leaks -no_track_allocs" doesn't solved the issue.
Using plain DynamoRIO the application start normaly.

**To Reproduce**
I join the application in debug (Just replace .zip by .exe) : [TestApp.zip](https://github.com/user-attachments/files/16611097/TestApp.zip)
Used command line is in description upper and I use a standalone version of Dr. Memory.

**Versions**
- Dr. Memory 2.6.0
- Lastest build is used to produce the issue
- Windows 10 Version 22H2 Build 19045.4651
- All application I tried is 32bit application

**Comment by derekbruening** [comment] 2024-10-08 15:57
Looks like a duplicate of https://github.com/DynamoRIO/drmemory/issues/2456. Some DynamoRIO issue with handling FLS (fiber-local-storage) in private libraries. Closing as duplicate to consolidate under https://github.com/DynamoRIO/drmemory/issues/2456.

**Closed by derekbruening** 2024-10-08 15:57 UTC
